export class Juego {
    constructor(
        public _id?: string,
        public _v?: string,
        public denominacion?: string | '',
        public descripcionGenerales?: string,
        public fechaAlta?: string,
        public creditoInicial?: string,
        public numeroSerie?: string,
        public token?: string| '',
        public documento?: string,
        public imgMontable?: string,
        public inmovilizado?: string,
        public valorAdquisicion?: string,
        public depreciacion?: string,
        public valorContable?: string,
        public comision?: string,
        public vidaUtil?: string,
        public proveedor?: string,
        public paisOrigen?: string,
        public subtotal?: string,
        public envio?: string,
        public total?: string,
        public fecha?: string,
        public observacion?: string,
        public noExterior?: string,
        public noInterior?: string,
        public referencia?: string,
        public comentarios?: string,
        public centroCosto?: string,
        public codigoPostal?: string,
        public estado?: string,
        public puntoVenta?: string,
        public tipo?: string,
        public consecutivo?: string,
        public usuario?: any,
    ){}
}